create_clock -period 10.000 -name clk_100 [get_ports clk_100]

set_property PACKAGE_PIN P17 [get_ports clk_100]
set_property PACKAGE_PIN P15 [get_ports rst_n]

set_property PACKAGE_PIN G2 [get_ports {tube_scan[7]}]
set_property PACKAGE_PIN C2 [get_ports {tube_scan[6]}]
set_property PACKAGE_PIN C1 [get_ports {tube_scan[5]}]
set_property PACKAGE_PIN H1 [get_ports {tube_scan[4]}]
set_property PACKAGE_PIN G1 [get_ports {tube_scan[3]}]
set_property PACKAGE_PIN F1 [get_ports {tube_scan[2]}]
set_property PACKAGE_PIN E1 [get_ports {tube_scan[1]}]
set_property PACKAGE_PIN G6 [get_ports {tube_scan[0]}]

set_property PACKAGE_PIN D4 [get_ports {tube_signal_right[7]}]
set_property PACKAGE_PIN E3 [get_ports {tube_signal_right[6]}]
set_property PACKAGE_PIN D3 [get_ports {tube_signal_right[5]}]
set_property PACKAGE_PIN F4 [get_ports {tube_signal_right[4]}]
set_property PACKAGE_PIN F3 [get_ports {tube_signal_right[3]}]
set_property PACKAGE_PIN E2 [get_ports {tube_signal_right[2]}]
set_property PACKAGE_PIN D2 [get_ports {tube_signal_right[1]}]
set_property PACKAGE_PIN H2 [get_ports {tube_signal_right[0]}]

set_property PACKAGE_PIN B4 [get_ports {tube_signal_left[7]}]
set_property PACKAGE_PIN A4 [get_ports {tube_signal_left[6]}]
set_property PACKAGE_PIN A3 [get_ports {tube_signal_left[5]}]
set_property PACKAGE_PIN B1 [get_ports {tube_signal_left[4]}]
set_property PACKAGE_PIN A1 [get_ports {tube_signal_left[3]}]
set_property PACKAGE_PIN B3 [get_ports {tube_signal_left[2]}]
set_property PACKAGE_PIN B2 [get_ports {tube_signal_left[1]}]
set_property PACKAGE_PIN D5 [get_ports {tube_signal_left[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk_100]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports {tube_scan[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_scan[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_scan[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_scan[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_scan[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_scan[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_scan[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_scan[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {tube_signal_left[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_signal_left[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_signal_left[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_signal_left[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_signal_left[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_signal_left[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_signal_left[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_signal_left[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {tube_signal_right[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_signal_right[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_signal_right[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_signal_right[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_signal_right[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_signal_right[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_signal_right[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tube_signal_right[0]}]